#!/bin/bash
case $1 in
    install)
        echo "INSTALLATION"
        useradd -d /home/snack snack -m -r -s /bin/false -U
        ;;
    upgrade)
        echo "UPGRADE from $2"
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        # Do nothing
        ;;
    *)
        echo "Unrecognized postinst argument '$1'"
        ;;
esac
exit 0
